/**
 * Helper to fetch from GitHub API
 */
async function ghFetch(repo, endpoint, token, options = {}) {
  const url = `https://api.github.com/repos/${repo}${endpoint}`;
  const res = await fetch(url, {
    ...options,
    headers: {
      "Accept": "application/vnd.github.v3+json",
      "Authorization": `token ${token}`,
      "Content-Type": "application/json",
      ...(options.headers || {})
    }
  });
  
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub API Error (${res.status}): ${err}`);
  }
  
  return res.json();
}

/**
 * Fetches the bootstrap snapshot JSON off GitHub Pages
 */
export async function fetchBootstrapSnapshot() {
  const targetRepo = localStorage.getItem('github_target_repo');
  if (!targetRepo) return [];
  
  console.log(`Fetching bootstrap snapshot from https://${targetRepo.split('/')[0]}.github.io/${targetRepo.split('/')[1]}/snapshot.json...`);
  
  try {
    // Attempt to pull from the GitHub Pages URL
    const res = await fetch(`https://${targetRepo.split('/')[0]}.github.io/${targetRepo.split('/')[1]}/snapshot.json?t=${Date.now()}`);
    if (res.ok) {
        return await res.json();
    }
    
    // Fallback: If not on pages yet, pull raw from main branch
    const rawRes = await fetch(`https://raw.githubusercontent.com/${targetRepo}/main/snapshot.json?t=${Date.now()}`);
    if (rawRes.ok) {
        return await rawRes.json();
    }
  } catch(e) {
    console.error('Failed to fetch snapshot on bootstrap. Initializing genesis state.', e);
  }
  
  return [];
}

/**
 * Validates logs and pushes PR with JSON updates.
 * Requires auth token for API calls.
 */
export async function createSnapshotPR(logs, token) {
  if (!token) {
    throw new Error('Not authorized for PR creation');
  }
  
  const repo = localStorage.getItem('github_target_repo');
  if (!repo) {
    throw new Error('No target repo configured (Check GitHub Auth settings)');
  }
  
  console.log('Crafting snapshot PR to ' + repo + '...');

  try {
    // 1. Get the current main branch reference SHA
    const refData = await ghFetch(repo, '/git/refs/heads/main', token);
    const mainSha = refData.object.sha;

    // 2. Create the blob for `snapshot.json`
    const blobData = await ghFetch(repo, '/git/blobs', token, {
      method: 'POST',
      body: JSON.stringify({
        content: JSON.stringify(logs, null, 2),
        encoding: 'utf-8'
      })
    });
    const blobSha = blobData.sha;

    // 3. Create a tree containing the new blob based on the main tree
    const treeData = await ghFetch(repo, '/git/trees', token, {
      method: 'POST',
      body: JSON.stringify({
        base_tree: mainSha,
        tree: [
          {
            path: 'snapshot.json',
            mode: '100644', // File
            type: 'blob',
            sha: blobSha
          }
        ]
      })
    });
    const treeSha = treeData.sha;

    // 4. Create a commit pointing to the new tree
    const commitData = await ghFetch(repo, '/git/commits', token, {
      method: 'POST',
      body: JSON.stringify({
        message: `chore: Decentralized network snapshot update (${logs.length} Pweets)`,
        tree: treeSha,
        parents: [mainSha]
      })
    });
    const newCommitSha = commitData.sha;

    // 5. Create a new branch pointing to the new commit
    const newBranchName = `refs/heads/snapshot-${Date.now()}`;
    await ghFetch(repo, '/git/refs', token, {
      method: 'POST',
      body: JSON.stringify({
        ref: newBranchName,
        sha: newCommitSha
      })
    });

    // 6. Create a Pull Request from the new branch to main
    const prData = await ghFetch(repo, '/pulls', token, {
      method: 'POST',
      body: JSON.stringify({
        title: `Automatic Snapshot Sync (${logs.length} events recorded)`,
        head: newBranchName.replace('refs/heads/', ''),
        base: 'main',
        body: `This PR was automatically generated by a Pweeter Node during a consensus round.\n\nIt contains **${logs.length}** decentralized log entries.\nMerge to automatically deploy the new snapshot to GitHub pages.`
      })
    });

    console.log('✅ PR Created successfully:', prData.html_url);
    alert(`Snapshot PR Created! Merge it here:\n${prData.html_url}`);
    
    return prData;
  } catch (err) {
    console.error('Snapshot PR Creation Failed:', err);
    alert(`Failed to create PR: ${err.message}`);
    throw err;
  }
}
